name: Job output
on:
  push:
    branches: [ main ]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:                                              
      job1_name: ${{ steps.set-output.outputs.name }}
    steps:                                                
      - name: set output
        id: set-output
        run: echo "name=Urgen Munikar" >> $GITHUB_OUTPUT
      - name: access output
        run: echo "Name: ${{ steps.set-output.outputs.name }}"

  job2:                                                  
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: access output
        run: echo "Name from job1 is ${{ needs.job1.outputs.job1_name }}"
