name: Manual Workflow

on:  
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Hello World!"
