name: Manual Workflow

on:  
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'

      age: 
        description: 'Age'
        type: number
        required: true

      gender:
        description: 'Gender'
        type: choice
        options:
          - Male
          - Female

      marriage:
        description: 'is Married?'
        type: boolean
        default: false

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "${{ inputs.name }}"
        
      - name: Age
        run: echo "${{ inputs.age }}"

      - name: Gender
        run: echo "${{ inputs.gender }}"

      - name: is Married?
        run: echo "${{ inputs.marriage }}"
