name: Schedule workflow

on: 
  workflow_dispatch:
  schedule:
      - cron: '*/10 * * * *'

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Log Time
        run: |
          current_date_time=$(date)
          echo "Current Date and Time: $current_date_time"
  
        
