name: Step Output

on:  
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: set output
        id: set-output
        shell: bash
        run: |
          echo "name=Urgen Munikar" >> $GITHUB_OUTPUT
          echo "age=22" >> $GITHUB_OUTPUT

      - name: access output
        run: echo "Name: ${{ steps.set-output.outputs.name}}"
        run: echo "Age: ${{ steps.set-output.outputs.age}}"
