name: Step Output

on:  
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: set output
        id: set-output
        shell: bash
        run: echo "age=24" >> $GITHUB_OUTPUT

      - name: access output
        run: echo ${{ steps.set-output.outputs.age}}
